name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      uses: bbbottle/bbp-action@build
    - name: release
      uses: bbbottle/bbp-action@v1.0.49
      with:
        hcp_client_id: ${{ secrets.HCP_CLIENT_ID }}
        hcp_client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
        wasm: "bbp_coc.wasm"